# Generated by Django 3.1.2 on 2020-10-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_auto_20201010_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
