# Generated by Django 3.1.2 on 2020-10-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0003_remove_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date']},
        ),
    ]
