# Generated by Django 3.1.2 on 2020-10-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0004_auto_20201010_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
